import type { PartnerOffer } from '@/lib/definitions';

export const offers: PartnerOffer[] = [
    {
        id: '1',
        slug: 'course-discount',
        title: 'Exclusive 20% Discount on All Courses',
        description: 'Enhance your skills with our comprehensive range of courses. As a valued partner, you get an exclusive 20% discount on all our offerings.',
        link: 'https://somepartner.com/courses',
        active: true,
        entitlement: {
            accessTier: 'standard',
            requiresLogin: true,
            requiresMembership: true,
            previewEnabled: false,
            isLimitedAccess: false,
            contentType: 'partner_offer_exclusive',
        },
        redemptionCode: 'PARTNER20',
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z',
    },
    {
        id: '2',
        slug: 'premium-analytics',
        title: 'Free Month of Premium Analytics',
        description: 'Get a free month of our premium analytics tool to gain deep insights into your business. No credit card required.',
        link: 'https://anotherpartner.com/analytics',
        active: true,
        entitlement: {
            accessTier: 'standard',
            requiresLogin: true,
            requiresMembership: true,
            previewEnabled: false,
            isLimitedAccess: false,
            contentType: 'partner_offer_exclusive',
        },
        redemptionCode: 'ANALYTICS30',
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z',
    },
    {
        id: '3',
        slug: 'early-access',
        title: 'Early Access to New Features',
        description: 'Be the first to experience our new features before they are released to the public. Your feedback will help shape the future of our product.',
        link: 'https://yet-another-partner.com/early-access',
        active: true,
        entitlement: {
            accessTier: 'premium',
            requiresLogin: true,
            requiresMembership: true,
            previewEnabled: false,
            isLimitedAccess: false,
            contentType: 'partner_offer_exclusive',
        },
        redemptionCode: 'EARLYBIRD',
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z',
    },
];
