export type NotificationRecipientType = 'user' | 'role' | 'queue' | 'tenant_admins' | 'workspace_group';
export type NotificationSeverity = 'info' | 'success' | 'warning' | 'error' | 'critical';
export type NotificationStatus = 'pending' | 'delivered' | 'read' | 'dismissed' | 'expired';
export type NotificationActionType = 'navigate' | 'api' | 'modal' | 'external';

export type NotificationAction = { key: string; label: string; type: NotificationActionType; route?: string; apiAction?: string; entityType?: string; entityId?: string; requiresConfirmation: boolean; isPrimary: boolean; enabled: boolean; disabledReason?: string };
export type Notification = {
  id: string;
  tenantId: string;
  workspaceId?: string;
  recipientType: NotificationRecipientType;
  recipientId: string;
  recipientScope?: string;
  notificationType: string;
  category: string;
  title: string;
  body: string;
  severity: NotificationSeverity;
  status: NotificationStatus;
  sourceSystem: 'platform' | 'odoo' | 'lending' | 'marble' | 'n8n';
  sourceEventType: string;
  relatedEntityType?: string;
  relatedEntityId?: string;
  relatedWorkflowInstanceId?: string;
  actions: NotificationAction[];
  channels: Array<'in_app' | 'email' | 'sms' | 'chat'>;
  dedupeKey?: string;
  createdAt: string;
  updatedAt: string;
  readAt?: string;
  dismissedAt?: string;
  expiresAt?: string;
  metadata: Record<string, unknown>;
  sourceRefs: Array<Record<string, unknown>>;
};
export type NotificationPreference = { id: string; tenantId: string; userId: string; notificationType?: string; category?: string; channelPreferences: Record<'in_app' | 'email' | 'sms' | 'chat', boolean>; muted: boolean; digestMode?: 'instant' | 'daily' | 'weekly'; createdAt: string; updatedAt: string };
export type CreateNotificationInput = Omit<Notification, 'id' | 'createdAt' | 'updatedAt' | 'status'> & { id?: string; status?: NotificationStatus };
export type NotificationQueryInput = { tenantId: string; recipientId: string; status?: 'read' | 'unread'; category?: string; notificationType?: string; severity?: NotificationSeverity; limit?: number; cursor?: string };
export type UpdateNotificationPreferenceInput = { notificationType?: string; category?: string; channelPreferences?: Partial<Record<'in_app' | 'email' | 'sms' | 'chat', boolean>>; muted?: boolean; digestMode?: 'instant' | 'daily' | 'weekly' };
export type NotificationDto = Notification;
export type NotificationListDto = { items: NotificationDto[]; summary: NotificationSummaryDto; pagination: { limit: number; total: number; nextCursor?: string } };
export type NotificationSummaryDto = { total: number; unread: number; highSeverity: number };
export type NotificationPreferenceDto = NotificationPreference;
