import type { ActionPolicyDefinition } from './types';

export const ACTION_POLICIES: ActionPolicyDefinition[] = [
  { id: 'search.query', actionKey: 'search.query', category: 'search', moduleKey: 'dashboard', requiredCapabilities: ['tasks.view'], requiredFeatureFlags: [], requiredModuleControls: ['dashboard'], tenantScoped: true, workspaceScoped: false, internalOnly: false, highRisk: false, auditOnAttempt: false, auditOnDeny: false },
  { id: 'tasks.list', actionKey: 'tasks.list', category: 'tasks', moduleKey: 'dashboard', requiredCapabilities: ['tasks.view'], requiredFeatureFlags: [], requiredModuleControls: ['dashboard'], tenantScoped: true, workspaceScoped: false, internalOnly: false, highRisk: false, auditOnAttempt: false, auditOnDeny: false },
  { id: 'tasks.assign', actionKey: 'tasks.assign', category: 'tasks', moduleKey: 'dashboard', requiredCapabilities: ['tasks.assign.execute'], requiredFeatureFlags: [], requiredModuleControls: ['dashboard'], tenantScoped: true, workspaceScoped: true, internalOnly: false, highRisk: true, auditOnAttempt: true, auditOnDeny: true },
  { id: 'tasks.complete', actionKey: 'tasks.complete', category: 'tasks', moduleKey: 'dashboard', requiredCapabilities: ['tasks.complete.execute'], requiredFeatureFlags: [], requiredModuleControls: ['dashboard'], tenantScoped: true, workspaceScoped: true, internalOnly: false, highRisk: true, auditOnAttempt: true, auditOnDeny: true },
  { id: 'workflows.review.start', actionKey: 'workflows.review.start', category: 'workflow', moduleKey: 'applications', requiredCapabilities: ['workflows.review.start'], requiredFeatureFlags: [], requiredModuleControls: ['applications'], tenantScoped: true, workspaceScoped: true, internalOnly: true, highRisk: true, auditOnAttempt: true, auditOnDeny: true },
  { id: 'workflows.review.approve', actionKey: 'workflows.review.approve', category: 'workflow', moduleKey: 'applications', requiredCapabilities: ['workflows.review.approve'], requiredFeatureFlags: [], requiredModuleControls: ['applications'], tenantScoped: true, workspaceScoped: true, internalOnly: true, highRisk: true, auditOnAttempt: true, auditOnDeny: true },
  { id: 'workflows.review.reject', actionKey: 'workflows.review.reject', category: 'workflow', moduleKey: 'applications', requiredCapabilities: ['workflows.review.reject'], requiredFeatureFlags: [], requiredModuleControls: ['applications'], tenantScoped: true, workspaceScoped: true, internalOnly: true, highRisk: true, auditOnAttempt: true, auditOnDeny: true },
  { id: 'workflows.review.request_more_info', actionKey: 'workflows.review.request_more_info', category: 'workflow', moduleKey: 'applications', requiredCapabilities: ['workflows.review.request_more_info'], requiredFeatureFlags: [], requiredModuleControls: ['applications'], tenantScoped: true, workspaceScoped: true, internalOnly: true, highRisk: true, auditOnAttempt: true, auditOnDeny: true },
  { id: 'applications.submit', actionKey: 'applications.submit', category: 'workflow', moduleKey: 'applications', requiredCapabilities: ['applications.submit.execute'], requiredFeatureFlags: [], requiredModuleControls: ['applications'], tenantScoped: true, workspaceScoped: true, internalOnly: true, highRisk: true, auditOnAttempt: true, auditOnDeny: true },
  { id: 'documents.upload', actionKey: 'documents.upload', category: 'workflow', moduleKey: 'documents', requiredCapabilities: ['documents.upload.execute'], requiredFeatureFlags: [], requiredModuleControls: ['documents'], tenantScoped: true, workspaceScoped: true, internalOnly: false, highRisk: true, auditOnAttempt: true, auditOnDeny: true },
  { id: 'support.escalate', actionKey: 'support.escalate', category: 'workflow', moduleKey: 'support', requiredCapabilities: ['support.escalate.execute'], requiredFeatureFlags: [], requiredModuleControls: ['support'], tenantScoped: true, workspaceScoped: true, internalOnly: false, highRisk: true, auditOnAttempt: true, auditOnDeny: true },
  { id: 'finance.billing_event.manage', actionKey: 'finance.billing_event.manage', category: 'workflow', moduleKey: 'finance', requiredCapabilities: ['finance.invoices.export'], requiredFeatureFlags: [], requiredModuleControls: ['finance'], tenantScoped: true, workspaceScoped: true, internalOnly: true, highRisk: true, auditOnAttempt: true, auditOnDeny: true },
  { id: 'admin.feature_assignment.create', actionKey: 'admin.feature_assignment.create', category: 'admin', moduleKey: 'admin', requiredCapabilities: ['admin.feature_flags.manage'], requiredFeatureFlags: [], requiredModuleControls: ['admin'], tenantScoped: false, workspaceScoped: false, internalOnly: true, highRisk: true, auditOnAttempt: true, auditOnDeny: true },
  { id: 'admin.feature_assignment.update', actionKey: 'admin.feature_assignment.update', category: 'admin', moduleKey: 'admin', requiredCapabilities: ['admin.feature_flags.manage'], requiredFeatureFlags: [], requiredModuleControls: ['admin'], tenantScoped: false, workspaceScoped: false, internalOnly: true, highRisk: true, auditOnAttempt: true, auditOnDeny: true },
  { id: 'admin.rollout.preview', actionKey: 'admin.rollout.preview', category: 'admin', moduleKey: 'admin', requiredCapabilities: ['admin.rollout.preview'], requiredFeatureFlags: [], requiredModuleControls: ['admin'], tenantScoped: false, workspaceScoped: false, internalOnly: true, highRisk: false, auditOnAttempt: false, auditOnDeny: true },
  { id: 'admin.module_rule.update', actionKey: 'admin.module_rule.update', category: 'admin', moduleKey: 'admin', requiredCapabilities: ['admin.module_controls.manage'], requiredFeatureFlags: [], requiredModuleControls: ['admin'], tenantScoped: false, workspaceScoped: false, internalOnly: true, highRisk: true, auditOnAttempt: true, auditOnDeny: true },
  { id: 'admin.audit.view', actionKey: 'admin.audit.view', category: 'admin', moduleKey: 'admin', requiredCapabilities: ['admin.audit.view'], requiredFeatureFlags: [], requiredModuleControls: ['admin'], tenantScoped: false, workspaceScoped: false, internalOnly: true, highRisk: false, auditOnAttempt: false, auditOnDeny: true },
];

export function getActionPolicy(actionKey: string) { return ACTION_POLICIES.find((item) => item.actionKey === actionKey) ?? null; }
