import type { RoutePolicyDefinition } from './types';

export const ROUTE_POLICIES: RoutePolicyDefinition[] = [
  { id: 'page.dashboard', pathPattern: '/dashboard', routeKind: 'protected_page', moduleKey: 'dashboard', requiredCapabilities: ['dashboard.view'], requiredFeatureFlags: [], requiredModuleControls: ['dashboard'], tenantScoped: true, workspaceScoped: false, internalOnly: false, adminOnly: false, hideFromNav: false, accessDeniedBehavior: 'redirect_login' },
  { id: 'page.portal.support', pathPattern: '/portal/support', routeKind: 'protected_page', moduleKey: 'support', requiredCapabilities: ['support.tickets.view'], requiredFeatureFlags: [], requiredModuleControls: ['support'], tenantScoped: true, workspaceScoped: true, internalOnly: false, adminOnly: false, hideFromNav: false, accessDeniedBehavior: 'render_access_denied' },
  { id: 'page.settings.profile', pathPattern: '/settings/profile', routeKind: 'protected_page', moduleKey: 'settings', requiredCapabilities: ['settings.profile.view'], requiredFeatureFlags: [], requiredModuleControls: ['settings'], tenantScoped: true, workspaceScoped: false, internalOnly: false, adminOnly: false, hideFromNav: false, accessDeniedBehavior: 'render_access_denied' },
  { id: 'page.admin.feature_controls', pathPattern: '/admin/system/feature-controls', routeKind: 'admin_page', moduleKey: 'admin', requiredCapabilities: ['admin.feature_flags.read'], requiredFeatureFlags: [], requiredModuleControls: ['admin'], tenantScoped: false, workspaceScoped: false, internalOnly: true, adminOnly: true, hideFromNav: false, accessDeniedBehavior: 'render_access_denied' },
  { id: 'page.admin.audit_logs', pathPattern: '/admin/audit-logs', routeKind: 'admin_page', moduleKey: 'admin', requiredCapabilities: ['admin.audit.view'], requiredFeatureFlags: [], requiredModuleControls: ['admin'], tenantScoped: false, workspaceScoped: false, internalOnly: true, adminOnly: true, hideFromNav: false, accessDeniedBehavior: 'render_access_denied' },
  { id: 'api.search', pathPattern: '/api/search', routeKind: 'api_endpoint', moduleKey: 'dashboard', requiredCapabilities: ['tasks.view'], requiredFeatureFlags: [], requiredModuleControls: ['dashboard'], tenantScoped: true, workspaceScoped: false, internalOnly: false, adminOnly: false, hideFromNav: true, accessDeniedBehavior: 'render_access_denied' },
  { id: 'api.tasks', pathPattern: '/api/tasks', routeKind: 'task_endpoint', moduleKey: 'dashboard', requiredCapabilities: ['tasks.view'], requiredFeatureFlags: [], requiredModuleControls: ['dashboard'], tenantScoped: true, workspaceScoped: false, internalOnly: false, adminOnly: false, hideFromNav: true, accessDeniedBehavior: 'render_access_denied' },
  { id: 'api.admin.feature_flags', pathPattern: '/api/admin/feature-flags', routeKind: 'api_endpoint', moduleKey: 'admin', requiredCapabilities: ['admin.feature_flags.read'], requiredFeatureFlags: [], requiredModuleControls: ['admin'], tenantScoped: false, workspaceScoped: false, internalOnly: true, adminOnly: true, hideFromNav: true, accessDeniedBehavior: 'render_access_denied' },
  { id: 'api.admin.module_controls', pathPattern: '/api/admin/module-controls', routeKind: 'api_endpoint', moduleKey: 'admin', requiredCapabilities: ['admin.module_controls.read'], requiredFeatureFlags: [], requiredModuleControls: ['admin'], tenantScoped: false, workspaceScoped: false, internalOnly: true, adminOnly: true, hideFromNav: true, accessDeniedBehavior: 'render_access_denied' },
  { id: 'api.admin.feature_preview', pathPattern: '/api/admin/feature-preview', routeKind: 'api_endpoint', moduleKey: 'admin', requiredCapabilities: ['admin.rollout.preview'], requiredFeatureFlags: [], requiredModuleControls: ['admin'], tenantScoped: false, workspaceScoped: false, internalOnly: true, adminOnly: true, hideFromNav: true, accessDeniedBehavior: 'render_access_denied' },
  { id: 'api.workflows.review_start', pathPattern: '/api/workflows/review-approval/start', routeKind: 'workflow_endpoint', moduleKey: 'applications', requiredCapabilities: ['workflows.review.start'], requiredFeatureFlags: [], requiredModuleControls: ['applications'], tenantScoped: true, workspaceScoped: true, internalOnly: true, adminOnly: false, hideFromNav: true, accessDeniedBehavior: 'render_access_denied' },
  { id: 'api.workflows.review_action', pathPattern: '/api/workflows/review-approval/', routeKind: 'workflow_endpoint', moduleKey: 'applications', requiredCapabilities: ['workflows.review.approve'], requiredFeatureFlags: [], requiredModuleControls: ['applications'], tenantScoped: true, workspaceScoped: true, internalOnly: true, adminOnly: false, hideFromNav: true, accessDeniedBehavior: 'render_access_denied' },
];

export function matchRoutePolicy(pathname: string) {
  return ROUTE_POLICIES.find((policy) => pathname === policy.pathPattern || pathname.startsWith(policy.pathPattern.endsWith('/') ? policy.pathPattern : `${policy.pathPattern}/`) || (policy.pathPattern.endsWith('/') && pathname.startsWith(policy.pathPattern))) ?? null;
}
