import type { FeatureFlagDefinition } from '@/lib/feature-flags/types';

export const FEATURE_FLAG_DEFINITIONS: FeatureFlagDefinition[] = [
  { key: 'feature.dashboard.enabled', name: 'Dashboard enabled', description: 'Controls dashboard feature availability.', category: 'dashboard', flagType: 'boolean', defaultValue: true, allowedScopes: ['environment', 'tenant', 'workspace', 'role', 'user'], releaseStage: 'general_availability', isKillSwitch: false, isInternalOnly: false, isDeprecated: false, dependencies: [], conflicts: [], tags: ['module'], owner: 'platform', createdBySystem: true },
  { key: 'feature.customers.enabled', name: 'Customers enabled', description: 'Controls customer workspace visibility.', category: 'customers', flagType: 'boolean', defaultValue: true, allowedScopes: ['environment', 'tenant', 'workspace', 'role', 'user'], releaseStage: 'general_availability', isKillSwitch: false, isInternalOnly: true, isDeprecated: false, dependencies: [], conflicts: [], tags: ['module'], owner: 'platform', createdBySystem: true },
  { key: 'feature.applications.enabled', name: 'Applications enabled', description: 'Controls applications capability.', category: 'applications', flagType: 'boolean', defaultValue: true, allowedScopes: ['environment', 'tenant', 'workspace', 'role', 'user'], releaseStage: 'general_availability', isKillSwitch: false, isInternalOnly: true, isDeprecated: false, dependencies: [], conflicts: [], tags: ['module'], owner: 'platform', createdBySystem: true },
  { key: 'feature.loans.enabled', name: 'Loans enabled', description: 'Controls loans capability.', category: 'loans', flagType: 'boolean', defaultValue: true, allowedScopes: ['environment', 'tenant', 'workspace', 'role', 'user'], releaseStage: 'limited', isKillSwitch: false, isInternalOnly: true, isDeprecated: false, dependencies: [], conflicts: [], tags: ['module'], owner: 'platform', createdBySystem: true },
  { key: 'feature.documents.enabled', name: 'Documents enabled', description: 'Controls documents capability.', category: 'documents', flagType: 'boolean', defaultValue: true, allowedScopes: ['environment', 'tenant', 'workspace', 'role', 'user'], releaseStage: 'general_availability', isKillSwitch: false, isInternalOnly: false, isDeprecated: false, dependencies: [], conflicts: [], tags: ['module'], owner: 'platform', createdBySystem: true },
  { key: 'feature.finance.enabled', name: 'Finance enabled', description: 'Controls finance capability.', category: 'finance', flagType: 'boolean', defaultValue: true, allowedScopes: ['environment', 'tenant', 'workspace', 'role', 'user'], releaseStage: 'general_availability', isKillSwitch: false, isInternalOnly: true, isDeprecated: false, dependencies: [], conflicts: [], tags: ['module'], owner: 'platform', createdBySystem: true },
  { key: 'feature.support.enabled', name: 'Support enabled', description: 'Controls support capability.', category: 'support', flagType: 'boolean', defaultValue: true, allowedScopes: ['environment', 'tenant', 'workspace', 'role', 'user'], releaseStage: 'general_availability', isKillSwitch: false, isInternalOnly: false, isDeprecated: false, dependencies: [], conflicts: [], tags: ['module'], owner: 'platform', createdBySystem: true },
  { key: 'feature.analytics.enabled', name: 'Analytics enabled', description: 'Controls analytics availability.', category: 'analytics', flagType: 'boolean', defaultValue: true, allowedScopes: ['environment', 'tenant', 'workspace', 'role', 'user'], releaseStage: 'beta', isKillSwitch: false, isInternalOnly: false, isDeprecated: false, dependencies: [], conflicts: [], tags: ['module', 'beta'], owner: 'platform', createdBySystem: true },
  { key: 'feature.search.enabled', name: 'Search enabled', description: 'Controls search capability.', category: 'search', flagType: 'boolean', defaultValue: true, allowedScopes: ['environment', 'tenant', 'workspace', 'role', 'user'], releaseStage: 'general_availability', isKillSwitch: false, isInternalOnly: false, isDeprecated: false, dependencies: [], conflicts: ['feature.kill_switch.search'], tags: ['capability'], owner: 'platform', createdBySystem: true },
  { key: 'feature.tasks.enabled', name: 'Tasks enabled', description: 'Controls task inbox capability.', category: 'tasks', flagType: 'boolean', defaultValue: true, allowedScopes: ['environment', 'tenant', 'workspace', 'role', 'user'], releaseStage: 'beta', isKillSwitch: false, isInternalOnly: false, isDeprecated: false, dependencies: [], conflicts: ['feature.kill_switch.tasks'], tags: ['capability', 'beta'], owner: 'platform', createdBySystem: true },
  { key: 'feature.notifications.enabled', name: 'Notifications enabled', description: 'Controls platform notifications.', category: 'notifications', flagType: 'boolean', defaultValue: true, allowedScopes: ['environment', 'tenant', 'workspace', 'role', 'user'], releaseStage: 'general_availability', isKillSwitch: false, isInternalOnly: false, isDeprecated: false, dependencies: [], conflicts: ['feature.kill_switch.notifications'], tags: ['capability'], owner: 'platform', createdBySystem: true },
  { key: 'feature.workflows.enabled', name: 'Workflows enabled', description: 'Controls workflow orchestration.', category: 'workflows', flagType: 'boolean', defaultValue: true, allowedScopes: ['environment', 'tenant', 'workspace', 'role', 'user'], releaseStage: 'general_availability', isKillSwitch: false, isInternalOnly: false, isDeprecated: false, dependencies: [], conflicts: ['feature.kill_switch.workflows'], tags: ['capability'], owner: 'platform', createdBySystem: true },
  { key: 'feature.module.admin.enabled', name: 'Admin module enabled', description: 'Controls admin module availability.', category: 'admin', flagType: 'boolean', defaultValue: true, allowedScopes: ['environment', 'tenant', 'workspace', 'role', 'user'], releaseStage: 'internal', isKillSwitch: false, isInternalOnly: true, isDeprecated: false, dependencies: [], conflicts: [], tags: ['module'], owner: 'platform', createdBySystem: true },
  { key: 'feature.module.settings.enabled', name: 'Settings module enabled', description: 'Controls settings module availability.', category: 'settings', flagType: 'boolean', defaultValue: true, allowedScopes: ['environment', 'tenant', 'workspace', 'role', 'user'], releaseStage: 'general_availability', isKillSwitch: false, isInternalOnly: false, isDeprecated: false, dependencies: [], conflicts: [], tags: ['module'], owner: 'platform', createdBySystem: true },
  { key: 'feature.internal.preview.customer360', name: 'Customer 360 preview', description: 'Internal preview for customer 360 experience.', category: 'customers', flagType: 'boolean', defaultValue: false, allowedScopes: ['environment', 'tenant', 'workspace', 'role', 'user'], releaseStage: 'internal', isKillSwitch: false, isInternalOnly: true, isDeprecated: false, dependencies: ['feature.customers.enabled'], conflicts: [], tags: ['preview'], owner: 'platform', createdBySystem: true },
  { key: 'feature.internal.preview.loan_workspace', name: 'Loan workspace preview', description: 'Preview access to loan workspace.', category: 'loans', flagType: 'boolean', defaultValue: false, allowedScopes: ['environment', 'tenant', 'workspace', 'role', 'user'], releaseStage: 'beta', isKillSwitch: false, isInternalOnly: true, isDeprecated: false, dependencies: ['feature.loans.enabled'], conflicts: [], tags: ['preview'], owner: 'platform', createdBySystem: true },
  { key: 'feature.kill_switch.search', name: 'Search kill switch', description: 'Emergency stop for search traffic.', category: 'search', flagType: 'boolean', defaultValue: false, allowedScopes: ['environment', 'tenant', 'workspace', 'role', 'user'], releaseStage: 'general_availability', isKillSwitch: true, isInternalOnly: true, isDeprecated: false, dependencies: [], conflicts: ['feature.search.enabled'], tags: ['kill-switch'], owner: 'platform', createdBySystem: true },
  { key: 'feature.kill_switch.tasks', name: 'Tasks kill switch', description: 'Emergency stop for task inbox.', category: 'tasks', flagType: 'boolean', defaultValue: false, allowedScopes: ['environment', 'tenant', 'workspace', 'role', 'user'], releaseStage: 'general_availability', isKillSwitch: true, isInternalOnly: true, isDeprecated: false, dependencies: [], conflicts: ['feature.tasks.enabled'], tags: ['kill-switch'], owner: 'platform', createdBySystem: true },
  { key: 'feature.kill_switch.notifications', name: 'Notifications kill switch', description: 'Emergency stop for notification creation and delivery.', category: 'notifications', flagType: 'boolean', defaultValue: false, allowedScopes: ['environment', 'tenant', 'workspace', 'role', 'user'], releaseStage: 'general_availability', isKillSwitch: true, isInternalOnly: true, isDeprecated: false, dependencies: [], conflicts: ['feature.notifications.enabled'], tags: ['kill-switch'], owner: 'platform', createdBySystem: true },
  { key: 'feature.kill_switch.workflows', name: 'Workflow kill switch', description: 'Emergency stop for workflow operations.', category: 'workflows', flagType: 'boolean', defaultValue: false, allowedScopes: ['environment', 'tenant', 'workspace', 'role', 'user'], releaseStage: 'general_availability', isKillSwitch: true, isInternalOnly: true, isDeprecated: false, dependencies: [], conflicts: ['feature.workflows.enabled'], tags: ['kill-switch'], owner: 'platform', createdBySystem: true },
  { key: 'feature.integration.odoo.readonly_mode', name: 'Odoo readonly mode', description: 'Blocks mutating Odoo operations.', category: 'integrations', flagType: 'boolean', defaultValue: false, allowedScopes: ['environment', 'tenant'], releaseStage: 'general_availability', isKillSwitch: false, isInternalOnly: false, isDeprecated: false, dependencies: [], conflicts: [], tags: ['integration', 'safety'], owner: 'platform', createdBySystem: true },
  { key: 'feature.integration.lending.readonly_mode', name: 'Lending readonly mode', description: 'Blocks mutating lending operations.', category: 'integrations', flagType: 'boolean', defaultValue: false, allowedScopes: ['environment', 'tenant'], releaseStage: 'general_availability', isKillSwitch: false, isInternalOnly: false, isDeprecated: false, dependencies: [], conflicts: [], tags: ['integration', 'safety'], owner: 'platform', createdBySystem: true },
  { key: 'feature.integration.marble.evaluation_enabled', name: 'Marble evaluation enabled', description: 'Allows Marble risk evaluation during workflows.', category: 'integrations', flagType: 'boolean', defaultValue: true, allowedScopes: ['environment', 'tenant', 'workspace'], releaseStage: 'limited', isKillSwitch: false, isInternalOnly: false, isDeprecated: false, dependencies: ['feature.workflows.enabled'], conflicts: [], tags: ['integration'], owner: 'platform', createdBySystem: true },
  { key: 'feature.integration.n8n.workflow_dispatch_enabled', name: 'n8n dispatch enabled', description: 'Allows workflow automation dispatch to n8n.', category: 'integrations', flagType: 'boolean', defaultValue: true, allowedScopes: ['environment', 'tenant', 'workspace'], releaseStage: 'general_availability', isKillSwitch: false, isInternalOnly: false, isDeprecated: false, dependencies: ['feature.workflows.enabled'], conflicts: ['feature.kill_switch.workflows'], tags: ['integration'], owner: 'platform', createdBySystem: true },
];

export function getFeatureFlagDefinition(flagKey: string) {
  return FEATURE_FLAG_DEFINITIONS.find((item) => item.key === flagKey);
}
