
export const members = [
    {
        id: "MEM-0001",
        fullName: "John Doe",
        email: "john.doe@example.com",
        company: "Stripe",
        membershipTier: "Premium",
        membershipStatus: "Active",
        joinDate: "2023-01-15",
        renewalDate: "2024-01-15",
        expiryDate: "2024-01-15",
        lastLogin: "2023-10-26",
        paymentStatus: "Paid",
        assignedAdmin: "Alice",
        tags: ["Lead", "New"],
        source: "Funnel",
    },
    {
        id: "MEM-0002",
        fullName: "Jane Smith",
        email: "jane.smith@example.com",
        company: "Google",
        membershipTier: "Standard",
        membershipStatus: "Trial",
        joinDate: "2023-09-01",
        renewalDate: "2023-10-01",
        expiryDate: "2023-10-01",
        lastLogin: "2023-10-20",
        paymentStatus: "No Subscription",
        assignedAdmin: "Bob",
        tags: ["Trial"],
        source: "Manual Signup",
    },
    {
        id: "MEM-0003",
        fullName: "Peter Jones",
        email: "peter.jones@example.com",
        company: "Microsoft",
        membershipTier: "Basic",
        membershipStatus: "Past Due",
        joinDate: "2023-05-20",
        renewalDate: "2023-10-20",
        expiryDate: "2023-10-20",
        lastLogin: "2023-10-15",
        paymentStatus: "Failed",
        assignedAdmin: "Alice",
        tags: ["Follow-up"],
        source: "Migrated",
    },
];
