import type { ModuleDefinition, ModuleKey, NavigationContext, ModuleCategory } from './types';

export const PLATFORM_MODULE_REGISTRY: ModuleDefinition[] = [
  {
    key: 'home',
    name: 'Home',
    description: 'Public-facing marketing and platform entry points.',
    category: 'foundation',
    route: '/',
    icon: 'Home',
    order: 10,
    isEnabledByDefault: true,
    isHidden: false,
    isInternalOnly: false,
    isBeta: false,
    requiredPermissions: [],
    requiredFeatureFlags: [],
    requiredTenantCapabilities: [],
    allowedWorkspaceTypes: [],
    children: ['knowledge', 'services', 'offers', 'docushare', 'help'],
    defaultLandingRoute: '/',
    navGroup: 'public',
    tags: ['public', 'marketing'],
  },
  {
    key: 'dashboard',
    name: 'Dashboard',
    description: 'Tenant-aware operational home for authenticated users.',
    category: 'foundation',
    route: '/dashboard',
    icon: 'LayoutDashboard',
    order: 20,
    isEnabledByDefault: true,
    isHidden: false,
    isInternalOnly: false,
    isBeta: false,
    requiredPermissions: [{ resource: 'dashboard', action: 'read' }],
    requiredFeatureFlags: [],
    requiredTenantCapabilities: [],
    allowedWorkspaceTypes: [],
    children: [],
    defaultLandingRoute: '/dashboard',
    navGroup: 'primary',
    tags: ['core'],
  },
  {
    key: 'customers',
    name: 'Customers',
    description: 'Customer, account, and relationship management views.',
    category: 'customer',
    route: '/admin/crm',
    icon: 'Users',
    order: 30,
    isEnabledByDefault: true,
    isHidden: false,
    isInternalOnly: true,
    isBeta: false,
    requiredPermissions: [{ resource: 'customer', action: 'read' }],
    requiredFeatureFlags: [],
    requiredTenantCapabilities: [],
    allowedWorkspaceTypes: ['operations', 'admin'],
    children: [],
    defaultLandingRoute: '/admin/crm',
    navGroup: 'admin',
    tags: ['internal', 'crm'],
  },
  {
    key: 'applications',
    name: 'Applications',
    description: 'Application intake and operational workflows.',
    category: 'operations',
    route: '/admin/services/discovery-calls',
    icon: 'FileText',
    order: 40,
    isEnabledByDefault: true,
    isHidden: false,
    isInternalOnly: true,
    isBeta: false,
    requiredPermissions: [{ resource: 'application', action: 'read' }],
    requiredFeatureFlags: [],
    requiredTenantCapabilities: [],
    allowedWorkspaceTypes: ['operations', 'admin'],
    children: [],
    defaultLandingRoute: '/admin/services/discovery-calls',
    navGroup: 'admin',
    tags: ['workflow'],
  },
  {
    key: 'documents',
    name: 'Documents',
    description: 'Document access, delivery, and management.',
    category: 'knowledge',
    route: '/portal/saved',
    icon: 'FileText',
    order: 50,
    isEnabledByDefault: true,
    isHidden: false,
    isInternalOnly: false,
    isBeta: false,
    requiredPermissions: [{ resource: 'document', action: 'read' }],
    requiredFeatureFlags: [],
    requiredTenantCapabilities: [],
    allowedWorkspaceTypes: [],
    children: ['docushare'],
    defaultLandingRoute: '/portal/saved',
    navGroup: 'workspace',
    tags: ['portal', 'docs'],
  },
  {
    key: 'finance',
    name: 'Finance',
    description: 'Billing, invoices, and finance operations.',
    category: 'finance',
    route: '/admin/membership/subscription-and-billing-oversight',
    icon: 'BadgeDollarSign',
    order: 60,
    isEnabledByDefault: true,
    isHidden: false,
    isInternalOnly: false,
    isBeta: false,
    requiredPermissions: [{ resource: 'finance', action: 'read' }],
    requiredFeatureFlags: [],
    requiredTenantCapabilities: [],
    allowedWorkspaceTypes: [],
    children: ['billing'],
    defaultLandingRoute: '/admin/membership/subscription-and-billing-oversight',
    navGroup: 'admin',
    tags: ['billing'],
  },
  {
    key: 'support',
    name: 'Support',
    description: 'Support cases, help requests, and ticket operations.',
    category: 'support',
    route: '/portal/support',
    icon: 'LifeBuoy',
    order: 70,
    isEnabledByDefault: true,
    isHidden: false,
    isInternalOnly: false,
    isBeta: false,
    requiredPermissions: [{ resource: 'support_ticket', action: 'read' }],
    requiredFeatureFlags: [],
    requiredTenantCapabilities: [],
    allowedWorkspaceTypes: [],
    children: ['help'],
    defaultLandingRoute: '/portal/support',
    navGroup: 'workspace',
    tags: ['portal', 'service'],
  },
  {
    key: 'knowledge',
    name: 'Knowledge',
    description: 'Knowledge center and reusable reference content.',
    category: 'knowledge',
    route: '/knowledge-center',
    icon: 'BookOpen',
    order: 80,
    isEnabledByDefault: true,
    isHidden: false,
    isInternalOnly: false,
    isBeta: false,
    requiredPermissions: [{ resource: 'knowledge', action: 'read' }],
    requiredFeatureFlags: [],
    requiredTenantCapabilities: [],
    allowedWorkspaceTypes: [],
    children: ['docushare', 'help'],
    defaultLandingRoute: '/knowledge-center',
    navGroup: 'public',
    tags: ['content'],
  },
  {
    key: 'services',
    name: 'Services',
    description: 'Services catalogue, discovery calls, and delivery workflows.',
    category: 'services',
    route: '/services',
    icon: 'Briefcase',
    order: 90,
    isEnabledByDefault: true,
    isHidden: false,
    isInternalOnly: false,
    isBeta: false,
    requiredPermissions: [],
    requiredFeatureFlags: [],
    requiredTenantCapabilities: [],
    allowedWorkspaceTypes: [],
    children: ['offers'],
    defaultLandingRoute: '/services',
    navGroup: 'public',
    tags: ['public', 'service'],
  },
  {
    key: 'analytics',
    name: 'Analytics',
    description: 'Operational reporting and embedded analytics.',
    category: 'analytics',
    route: '/admin/analytics',
    icon: 'LineChart',
    order: 100,
    isEnabledByDefault: true,
    isHidden: false,
    isInternalOnly: false,
    isBeta: true,
    requiredPermissions: [{ resource: 'analytics', action: 'read' }],
    requiredFeatureFlags: ['analytics_embeds'],
    requiredTenantCapabilities: [],
    allowedWorkspaceTypes: [],
    children: [],
    defaultLandingRoute: '/admin/analytics',
    navGroup: 'admin',
    tags: ['reporting'],
    badges: [{ key: 'beta', label: 'Beta', variant: 'info' }],
  },
  {
    key: 'settings',
    name: 'Settings',
    description: 'Profile, team, security, and tenant-level settings.',
    category: 'security',
    route: '/settings/profile',
    icon: 'Settings',
    order: 110,
    isEnabledByDefault: true,
    isHidden: false,
    isInternalOnly: false,
    isBeta: false,
    requiredPermissions: [{ resource: 'settings', action: 'read' }],
    requiredFeatureFlags: [],
    requiredTenantCapabilities: [],
    allowedWorkspaceTypes: [],
    children: ['profile', 'membership'],
    defaultLandingRoute: '/settings/profile',
    navGroup: 'user',
    tags: ['account'],
  },
  {
    key: 'admin',
    name: 'Admin',
    description: 'Internal administrative console and system operations.',
    category: 'admin',
    route: '/admin',
    icon: 'ShieldCheck',
    order: 120,
    isEnabledByDefault: true,
    isHidden: false,
    isInternalOnly: true,
    isBeta: false,
    requiredPermissions: [{ resource: 'admin_user', action: 'read' }],
    requiredFeatureFlags: ['admin_console'],
    requiredTenantCapabilities: [],
    allowedWorkspaceTypes: ['admin'],
    children: ['customers', 'applications', 'finance', 'support', 'analytics'],
    defaultLandingRoute: '/admin',
    navGroup: 'admin',
    tags: ['internal'],
  },
  {
    key: 'membership',
    name: 'Membership',
    description: 'Member portal membership and entitlement flows.',
    category: 'services',
    route: '/portal/membership',
    icon: 'Star',
    order: 130,
    isEnabledByDefault: true,
    isHidden: false,
    isInternalOnly: false,
    isBeta: false,
    requiredPermissions: [{ resource: 'dashboard', action: 'read' }],
    requiredFeatureFlags: [],
    requiredTenantCapabilities: [],
    allowedWorkspaceTypes: [],
    children: [],
    defaultLandingRoute: '/portal/membership',
    navGroup: 'workspace',
    tags: ['portal'],
  },
  {
    key: 'billing',
    name: 'Billing',
    description: 'Billing and subscription views for members.',
    category: 'finance',
    route: '/portal/subscription',
    icon: 'CreditCard',
    order: 140,
    isEnabledByDefault: true,
    isHidden: false,
    isInternalOnly: false,
    isBeta: false,
    requiredPermissions: [{ resource: 'settings', action: 'read' }],
    requiredFeatureFlags: [],
    requiredTenantCapabilities: [],
    allowedWorkspaceTypes: [],
    children: [],
    defaultLandingRoute: '/portal/subscription',
    navGroup: 'workspace',
    tags: ['portal', 'billing'],
  },
  {
    key: 'offers',
    name: 'Offers',
    description: 'Partner offers and value-added programs.',
    category: 'marketing',
    route: '/partner-offers',
    icon: 'Gift',
    order: 150,
    isEnabledByDefault: true,
    isHidden: false,
    isInternalOnly: false,
    isBeta: false,
    requiredPermissions: [],
    requiredFeatureFlags: [],
    requiredTenantCapabilities: [],
    allowedWorkspaceTypes: [],
    children: [],
    defaultLandingRoute: '/partner-offers',
    navGroup: 'public',
    tags: ['marketing'],
  },
  {
    key: 'docushare',
    name: 'DocuShare',
    description: 'Structured documentation and templates library.',
    category: 'knowledge',
    route: '/docushare',
    icon: 'FileStack',
    order: 160,
    isEnabledByDefault: true,
    isHidden: false,
    isInternalOnly: false,
    isBeta: false,
    requiredPermissions: [],
    requiredFeatureFlags: [],
    requiredTenantCapabilities: [],
    allowedWorkspaceTypes: [],
    children: [],
    defaultLandingRoute: '/docushare',
    navGroup: 'public',
    tags: ['docs'],
  },
  {
    key: 'help',
    name: 'Help Centre',
    description: 'Help, support, and assistance touchpoints.',
    category: 'support',
    route: '/support',
    icon: 'CircleHelp',
    order: 170,
    isEnabledByDefault: true,
    isHidden: false,
    isInternalOnly: false,
    isBeta: false,
    requiredPermissions: [],
    requiredFeatureFlags: [],
    requiredTenantCapabilities: [],
    allowedWorkspaceTypes: [],
    children: [],
    defaultLandingRoute: '/support',
    navGroup: 'public',
    tags: ['help'],
  },
  {
    key: 'profile',
    name: 'Profile',
    description: 'Personal profile and security settings.',
    category: 'security',
    route: '/settings/profile',
    icon: 'User',
    order: 180,
    isEnabledByDefault: true,
    isHidden: false,
    isInternalOnly: false,
    isBeta: false,
    requiredPermissions: [{ resource: 'settings', action: 'read' }],
    requiredFeatureFlags: [],
    requiredTenantCapabilities: [],
    allowedWorkspaceTypes: [],
    children: [],
    defaultLandingRoute: '/settings/profile',
    navGroup: 'user',
    tags: ['user'],
  },
];

export function getAllModules() {
  return [...PLATFORM_MODULE_REGISTRY].sort((a, b) => a.order - b.order);
}

export function getModuleByKey(key: ModuleKey) {
  return PLATFORM_MODULE_REGISTRY.find((module) => module.key === key);
}

export function listModulesByCategory(category: ModuleCategory) {
  return getAllModules().filter((module) => module.category === category);
}

export function listModulesByNavGroup(navGroup: ModuleDefinition['navGroup']) {
  return getAllModules().filter((module) => module.navGroup === navGroup);
}

export function listVisibleModules(context: NavigationContext) {
  return getAllModules().filter((module) => context.enabledModules.includes(module.key));
}
