import type { ModuleDefinition, NavigationGroupKey, ModuleCategory } from './types';

export const PLATFORM_MODULE_REGISTRY: ModuleDefinition[] = [
  {
    key: 'home',
    name: 'Home',
    description: 'Public-facing marketing and platform entry points.',
    category: 'public',
    route: '/',
    icon: 'Home',
    isEnabledByDefault: true,
    isHidden: false,
    isInternalOnly: false,
    requiredPermissions: [],
    requiredFeatureFlags: [],
  },
  {
    key: 'dashboard',
    name: 'Dashboard',
    description: 'Tenant-aware operational home for authenticated users.',
    category: 'core',
    route: '/dashboard',
    icon: 'LayoutDashboard',
    isEnabledByDefault: true,
    isHidden: false,
    isInternalOnly: false,
    requiredPermissions: [{ resource: 'dashboard', action: 'read' }],
    requiredFeatureFlags: [],
  },
  {
    key: 'customers',
    name: 'Customers',
    description: 'Customer, account, and relationship management views.',
    category: 'operations',
    route: '/admin/crm',
    icon: 'Users',
    isEnabledByDefault: true,
    isHidden: false,
    isInternalOnly: true,
    requiredPermissions: [{ resource: 'customer', action: 'read' }],
    requiredFeatureFlags: [],
  },
  {
    key: 'applications',
    name: 'Applications',
    description: 'Public-facing application and solutions marketing.',
    category: 'public',
    route: '/applications',
    icon: 'AppWindow',
    isEnabledByDefault: true,
    isHidden: false,
    isInternalOnly: false,
    requiredPermissions: [],
    requiredFeatureFlags: [],
  },
  {
    key: 'documents',
    name: 'Documents',
    description: 'Document access, delivery, and management.',
    category: 'service',
    route: '/portal/saved',
    icon: 'FileText',
    isEnabledByDefault: true,
    isHidden: false,
    isInternalOnly: false,
    requiredPermissions: [{ resource: 'document', action: 'read' }],
    requiredFeatureFlags: [],
  },
  {
    key: 'finance',
    name: 'Finance',
    description: 'Billing, invoices, and finance operations.',
    category: 'system',
    route: '/admin/membership/subscription-and-billing-oversight',
    icon: 'BadgeDollarSign',
    isEnabledByDefault: true,
    isHidden: false,
    isInternalOnly: true,
    requiredPermissions: [{ resource: 'finance', action: 'read' }],
    requiredFeatureFlags: [],
  },
  {
    key: 'support',
    name: 'Support',
    description: 'Support cases, help requests, and ticket operations.',
    category: 'service',
    route: '/portal/support',
    icon: 'LifeBuoy',
    isEnabledByDefault: true,
    isHidden: false,
    isInternalOnly: false,
    requiredPermissions: [{ resource: 'support_ticket', action: 'read' }],
    requiredFeatureFlags: [],
  },
  {
    key: 'knowledge',
    name: 'Resources',
    description: 'Knowledge center and reusable reference content.',
    category: 'public',
    route: '/resources',
    icon: 'BookOpen',
    isEnabledByDefault: true,
    isHidden: false,
    isInternalOnly: false,
    requiredPermissions: [],
    requiredFeatureFlags: [],
  },
  {
    key: 'services',
    name: 'Services',
    description: 'Services catalogue, discovery calls, and delivery workflows.',
    category: 'public',
    route: '/services',
    icon: 'Briefcase',
    isEnabledByDefault: true,
    isHidden: false,
    isInternalOnly: false,
    requiredPermissions: [],
    requiredFeatureFlags: [],
  },
  {
    key: 'analytics',
    name: 'Analytics',
    description: 'Operational reporting and embedded analytics.',
    category: 'intelligence',
    route: '/admin/analytics',
    icon: 'LineChart',
    isEnabledByDefault: true,
    isHidden: false,
    isInternalOnly: true,
    requiredPermissions: [{ resource: 'analytics', action: 'read' }],
    requiredFeatureFlags: ['analytics_embeds'],
  },
  {
    key: 'settings',
    name: 'Settings',
    description: 'Profile, team, security, and tenant-level settings.',
    category: 'system',
    route: '/settings/profile',
    icon: 'Settings',
    isEnabledByDefault: true,
    isHidden: false,
    isInternalOnly: false,
    requiredPermissions: [{ resource: 'settings', action: 'read' }],
    requiredFeatureFlags: [],
  },
  {
    key: 'admin',
    name: 'Admin',
    description: 'Internal administrative console and system operations.',
    category: 'system',
    route: '/admin',
    icon: 'ShieldCheck',
    isEnabledByDefault: true,
    isHidden: false,
    isInternalOnly: true,
    requiredPermissions: [{ resource: 'admin_user', action: 'read' }],
    requiredFeatureFlags: ['admin_console'],
  },
  {
    key: 'membership',
    name: 'Membership',
    description: 'Member portal membership and entitlement flows.',
    category: 'service',
    route: '/portal/membership',
    icon: 'Star',
    isEnabledByDefault: true,
    isHidden: true, // Hidden from public nav
    isInternalOnly: false,
    requiredPermissions: [{ resource: 'dashboard', action: 'read' }],
    requiredFeatureFlags: [],
  },
  {
    key: 'billing',
    name: 'Billing',
    description: 'Billing and subscription views for members.',
    category: 'service',
    route: '/portal/subscription',
    icon: 'CreditCard',
    isEnabledByDefault: true,
    isHidden: false,
    isInternalOnly: false,
    requiredPermissions: [{ resource: 'settings', action: 'read' }],
    requiredFeatureFlags: [],
  },
  {
    key: 'offers',
    name: 'Offers',
    description: 'Partner offers and value-added programs.',
    category: 'public',
    route: '/offers',
    icon: 'Gift',
    isEnabledByDefault: true,
    isHidden: false,
    isInternalOnly: false,
    requiredPermissions: [],
    requiredFeatureFlags: [],
  },
  {
    key: 'docushare',
    name: 'DocuShare',
    description: 'Structured documentation and templates library.',
    category: 'public',
    route: '/docushare',
    icon: 'FileStack',
    isEnabledByDefault: true,
    isHidden: false,
    isInternalOnly: false,
    requiredPermissions: [],
    requiredFeatureFlags: [],
  },
  {
    key: 'help',
    name: 'Help Centre',
    description: 'Help, support, and assistance touchpoints.',
    category: 'service',
    route: '/support', // This is now an internal route
    icon: 'CircleHelp',
    isEnabledByDefault: true,
    isHidden: true, // Hidden from public nav
    isInternalOnly: false,
    requiredPermissions: [],
    requiredFeatureFlags: [],
  },
  {
    key: 'profile',
    name: 'Profile',
    description: 'Personal profile and security settings.',
    category: 'system',
    route: '/settings/profile',
    icon: 'User',
    isEnabledByDefault: true,
    isHidden: false,
    isInternalOnly: false,
    requiredPermissions: [{ resource: 'settings', action: 'read' }],
    requiredFeatureFlags: [],
  },
];

export function getAllModules() {
  return [...PLATFORM_MODULE_REGISTRY].sort((a, b) => (a.name > b.name ? 1 : -1));
}

export function getModuleByKey(key: ModuleDefinition['key']) {
  return PLATFORM_MODULE_REGISTRY.find((module) => module.key === key);
}

export function listModulesByCategory(category: ModuleCategory) {
  return getAllModules().filter((module) => module.category === category);
}

export function listModulesByNavGroup(navGroup: NavigationGroupKey) {
  return getAllModules().filter((module) => (module as any).navGroup === navGroup);
}
