import type { NavigationGroupKey, RouteDefinition } from './types';

const route = (definition: RouteDefinition) => definition;
const nav = (navGroup: NavigationGroupKey) => navGroup;

export const PLATFORM_ROUTE_DEFINITIONS: RouteDefinition[] = [
  route({ id: 'public.home', path: '/', moduleKey: 'home', routeType: 'public', label: 'Home', requiredPermissions: [], requiredFeatureFlags: [], requiredTenantCapabilities: [], requiredModules: ['home'], allowAnonymous: true, hideFromNav: false, navGroup: nav('public'), isDefaultLanding: true, isEnabled: true, order: 10, icon: 'Home', accessDeniedBehavior: 'redirect' }),
  route({ id: 'public.about', path: '/about', moduleKey: 'home', routeType: 'public', label: 'About', requiredPermissions: [], requiredFeatureFlags: [], requiredTenantCapabilities: [], requiredModules: ['home'], allowAnonymous: true, hideFromNav: false, navGroup: nav('public'), isDefaultLanding: false, isEnabled: true, order: 20, icon: 'Info', accessDeniedBehavior: 'hide' }),
  route({ id: 'public.services', path: '/services', moduleKey: 'services', routeType: 'public', label: 'Services', requiredPermissions: [], requiredFeatureFlags: [], requiredTenantCapabilities: [], requiredModules: ['services'], allowAnonymous: true, hideFromNav: false, navGroup: nav('public'), isDefaultLanding: false, isEnabled: true, order: 30, icon: 'Briefcase', accessDeniedBehavior: 'hide', matchPrefixes: ['/services'] }),
  route({ id: 'public.docushare', path: '/docushare', moduleKey: 'docushare', routeType: 'public', label: 'DocuShare', requiredPermissions: [], requiredFeatureFlags: [], requiredTenantCapabilities: [], requiredModules: ['docushare'], allowAnonymous: true, hideFromNav: false, navGroup: nav('public'), isDefaultLanding: false, isEnabled: true, order: 40, icon: 'FileStack', accessDeniedBehavior: 'hide', matchPrefixes: ['/docushare'] }),
  route({ id: 'public.offers', path: '/offers', moduleKey: 'offers', routeType: 'public', label: 'Offers', requiredPermissions: [], requiredFeatureFlags: [], requiredTenantCapabilities: [], requiredModules: ['offers'], allowAnonymous: true, hideFromNav: false, navGroup: nav('public'), isDefaultLanding: false, isEnabled: true, order: 50, icon: 'Gift', accessDeniedBehavior: 'hide', matchPrefixes: ['/offers'] }),
  route({ id: 'public.applications', path: '/applications', moduleKey: 'applications', routeType: 'public', label: 'Applications', requiredPermissions: [], requiredFeatureFlags: [], requiredTenantCapabilities: [], requiredModules: ['applications'], allowAnonymous: true, hideFromNav: false, navGroup: nav('public'), isDefaultLanding: false, isEnabled: true, order: 60, icon: 'AppWindow', accessDeniedBehavior: 'hide' }),
  route({ id: 'public.resources', path: '/resources', moduleKey: 'knowledge', routeType: 'public', label: 'Resources', requiredPermissions: [], requiredFeatureFlags: [], requiredTenantCapabilities: [], requiredModules: ['knowledge'], allowAnonymous: true, hideFromNav: false, navGroup: nav('public'), isDefaultLanding: false, isEnabled: true, order: 70, icon: 'BookOpen', accessDeniedBehavior: 'hide', matchPrefixes: ['/resources'] }),
  route({ id: 'public.contact', path: '/contact', moduleKey: 'home', routeType: 'public', label: 'Contact', requiredPermissions: [], requiredFeatureFlags: [], requiredTenantCapabilities: [], requiredModules: ['home'], allowAnonymous: true, hideFromNav: false, navGroup: nav('public'), isDefaultLanding: false, isEnabled: true, order: 80, icon: 'Mail', accessDeniedBehavior: 'hide' }),
  route({ id: 'auth.login', path: '/login', moduleKey: 'home', routeType: 'public', label: 'Sign in', requiredPermissions: [], requiredFeatureFlags: [], requiredTenantCapabilities: [], requiredModules: ['home'], allowAnonymous: true, hideFromNav: true, navGroup: nav('public'), isDefaultLanding: false, isEnabled: true, order: 999, accessDeniedBehavior: 'redirect' }),
  
  // All other routes are preserved below
  route({ id: 'tenant.dashboard', path: '/dashboard', moduleKey: 'dashboard', routeType: 'tenant', label: 'Dashboard', requiredPermissions: [{ resource: 'dashboard', action: 'read' }], requiredFeatureFlags: [], requiredTenantCapabilities: [], requiredModules: ['dashboard'], allowAnonymous: false, hideFromNav: false, navGroup: nav('primary'), isDefaultLanding: true, isEnabled: true, order: 10, icon: 'LayoutDashboard', accessDeniedBehavior: 'redirect' }),
  route({ id: 'portal.overview', path: '/portal', moduleKey: 'dashboard', routeType: 'tenant', label: 'Overview', requiredPermissions: [{ resource: 'dashboard', action: 'read' }], requiredFeatureFlags: [], requiredTenantCapabilities: [], requiredModules: ['dashboard'], allowAnonymous: false, hideFromNav: false, navGroup: nav('workspace'), isDefaultLanding: false, isEnabled: true, order: 20, icon: 'LayoutDashboard', accessDeniedBehavior: 'redirect' }),
  route({ id: 'portal.membership', path: '/portal/membership', moduleKey: 'membership', routeType: 'tenant', label: 'Membership', requiredPermissions: [{ resource: 'dashboard', action: 'read' }], requiredFeatureFlags: [], requiredTenantCapabilities: [], requiredModules: ['membership'], allowAnonymous: false, hideFromNav: false, navGroup: nav('workspace'), isDefaultLanding: false, isEnabled: true, order: 30, icon: 'Star', accessDeniedBehavior: 'render_access_denied' }),
  route({ id: 'portal.subscription', path: '/portal/subscription', moduleKey: 'billing', routeType: 'tenant', label: 'Billing & Subscription', requiredPermissions: [{ resource: 'settings', action: 'read' }], requiredFeatureFlags: [], requiredTenantCapabilities: [], requiredModules: ['billing'], allowAnonymous: false, hideFromNav: false, navGroup: nav('workspace'), isDefaultLanding: false, isEnabled: true, order: 40, icon: 'CreditCard', accessDeniedBehavior: 'render_access_denied' }),
  route({ id: 'portal.saved', path: '/portal/saved', moduleKey: 'documents', routeType: 'tenant', label: 'Saved & Recent', requiredPermissions: [{ resource: 'document', action: 'read' }], requiredFeatureFlags: [], requiredTenantCapabilities: [], requiredModules: ['documents'], allowAnonymous: false, hideFromNav: false, navGroup: nav('workspace'), isDefaultLanding: false, isEnabled: true, order: 50, icon: 'FileText', accessDeniedBehavior: 'render_access_denied' }),
  route({ id: 'portal.support', path: '/portal/support', moduleKey: 'support', routeType: 'tenant', label: 'Support Requests', requiredPermissions: [{ resource: 'support_ticket', action: 'read' }], requiredFeatureFlags: [], requiredTenantCapabilities: [], requiredModules: ['support'], allowAnonymous: false, hideFromNav: false, navGroup: nav('workspace'), isDefaultLanding: false, isEnabled: true, order: 60, icon: 'LifeBuoy', accessDeniedBehavior: 'render_access_denied' }),
  route({ id: 'portal.discoveryCalls', path: '/portal/discovery-calls', moduleKey: 'services', routeType: 'tenant', label: 'Discovery Calls', requiredPermissions: [{ resource: 'dashboard', action: 'read' }], requiredFeatureFlags: [], requiredTenantCapabilities: [], requiredModules: ['services'], allowAnonymous: false, hideFromNav: false, navGroup: nav('workspace'), isDefaultLanding: false, isEnabled: true, order: 70, icon: 'Briefcase', accessDeniedBehavior: 'render_access_denied' }),
  route({ id: 'portal.customisationRequests', path: '/portal/customisation-requests', moduleKey: 'services', routeType: 'tenant', label: 'Customisation Requests', requiredPermissions: [{ resource: 'dashboard', action: 'read' }], requiredFeatureFlags: [], requiredTenantCapabilities: [], requiredModules: ['services'], allowAnonymous: false, hideFromNav: false, navGroup: nav('workspace'), isDefaultLanding: false, isEnabled: true, order: 80, icon: 'Briefcase', accessDeniedBehavior: 'render_access_denied' }),
  route({ id: 'portal.profile', path: '/portal/profile', moduleKey: 'profile', routeType: 'authenticated', label: 'Profile', requiredPermissions: [{ resource: 'settings', action: 'read' }], requiredFeatureFlags: [], requiredTenantCapabilities: [], requiredModules: ['profile'], allowAnonymous: false, hideFromNav: true, navGroup: nav('user'), isDefaultLanding: false, isEnabled: true, order: 90, icon: 'User', accessDeniedBehavior: 'render_access_denied' }),
  route({ id: 'settings.profile', path: '/settings/profile', moduleKey: 'profile', routeType: 'authenticated', label: 'Profile', requiredPermissions: [{ resource: 'settings', action: 'read' }], requiredFeatureFlags: [], requiredTenantCapabilities: [], requiredModules: ['settings', 'profile'], allowAnonymous: false, hideFromNav: false, navGroup: nav('user'), isDefaultLanding: true, isEnabled: true, order: 10, icon: 'User', accessDeniedBehavior: 'render_access_denied', matchPrefixes: ['/settings/profile'] }),
  route({ id: 'settings.security', path: '/settings/security', moduleKey: 'settings', routeType: 'authenticated', label: 'Security', requiredPermissions: [{ resource: 'settings', action: 'read' }], requiredFeatureFlags: [], requiredTenantCapabilities: [], requiredModules: ['settings'], allowAnonymous: false, hideFromNav: false, navGroup: nav('user'), isDefaultLanding: false, isEnabled: true, order: 20, icon: 'ShieldCheck', accessDeniedBehavior: 'render_access_denied', matchPrefixes: ['/settings/security'] }),
  route({ id: 'settings.notifications', path: '/settings/notifications', moduleKey: 'settings', routeType: 'authenticated', label: 'Notifications', requiredPermissions: [{ resource: 'settings', action: 'read' }], requiredFeatureFlags: [], requiredTenantCapabilities: [], requiredModules: ['settings'], allowAnonymous: false, hideFromNav: false, navGroup: nav('user'), isDefaultLanding: false, isEnabled: true, order: 30, icon: 'Bell', accessDeniedBehavior: 'render_access_denied', matchPrefixes: ['/settings/notifications'] }),
  route({ id: 'settings.team', path: '/settings/team', moduleKey: 'settings', routeType: 'authenticated', label: 'Team', requiredPermissions: [{ resource: 'settings', action: 'read' }], requiredFeatureFlags: [], requiredTenantCapabilities: [], requiredModules: ['settings'], allowAnonymous: false, hideFromNav: false, navGroup: nav('user'), isDefaultLanding: false, isEnabled: true, order: 40, icon: 'Users', accessDeniedBehavior: 'render_access_denied', matchPrefixes: ['/settings/team'] }),
  route({ id: 'settings.company', path: '/settings/company', moduleKey: 'settings', routeType: 'authenticated', label: 'Company', requiredPermissions: [{ resource: 'settings', action: 'read' }], requiredFeatureFlags: [], requiredTenantCapabilities: [], requiredModules: ['settings'], allowAnonymous: false, hideFromNav: false, navGroup: nav('user'), isDefaultLanding: false, isEnabled: true, order: 50, icon: 'Building2', accessDeniedBehavior: 'render_access_denied', matchPrefixes: ['/settings/company'] }),
  route({ id: 'admin.dashboard', path: '/admin', moduleKey: 'admin', routeType: 'admin', label: 'Admin Dashboard', requiredPermissions: [{ resource: 'admin_user', action: 'read' }], requiredFeatureFlags: ['admin_console'], requiredTenantCapabilities: [], requiredModules: ['admin'], allowAnonymous: false, hideFromNav: false, navGroup: nav('admin'), isDefaultLanding: true, isEnabled: true, order: 10, icon: 'LayoutDashboard', accessDeniedBehavior: 'render_access_denied' }),
  route({ id: 'admin.crm', path: '/admin/crm', moduleKey: 'customers', routeType: 'admin', label: 'CRM', requiredPermissions: [{ resource: 'customer', action: 'read' }], requiredFeatureFlags: [], requiredTenantCapabilities: [], requiredModules: ['customers'], allowAnonymous: false, hideFromNav: false, navGroup: nav('admin'), isDefaultLanding: false, isEnabled: true, order: 20, icon: 'Users', accessDeniedBehavior: 'render_access_denied', matchPrefixes: ['/admin/crm'] }),
  route({ id: 'admin.members', path: '/admin/membership/member-administration', moduleKey: 'admin', routeType: 'admin', label: 'Members', requiredPermissions: [{ resource: 'admin_user', action: 'read' }], requiredFeatureFlags: ['admin_console'], requiredTenantCapabilities: [], requiredModules: ['admin'], allowAnonymous: false, hideFromNav: false, navGroup: nav('admin'), isDefaultLanding: false, isEnabled: true, order: 30, icon: 'Users', accessDeniedBehavior: 'render_access_denied', matchPrefixes: ['/admin/membership/member-administration', '/admin/membership/members'] }),
  route({ id: 'admin.billing', path: '/admin/membership/subscription-and-billing-oversight', moduleKey: 'finance', routeType: 'admin', label: 'Billing', requiredPermissions: [{ resource: 'finance', action: 'read' }], requiredFeatureFlags: [], requiredTenantCapabilities: [], requiredModules: ['finance'], allowAnonymous: false, hideFromNav: false, navGroup: nav('admin'), isDefaultLanding: false, isEnabled: true, order: 40, icon: 'BadgeDollarSign', accessDeniedBehavior: 'render_access_denied', matchPrefixes: ['/admin/membership/subscription-and-billing-oversight'] }),
  route({ id: 'admin.analytics', path: '/admin/analytics', moduleKey: 'analytics', routeType: 'admin', label: 'Analytics', requiredPermissions: [{ resource: 'analytics', action: 'read' }], requiredFeatureFlags: ['analytics_embeds'], requiredTenantCapabilities: [], requiredModules: ['analytics'], allowAnonymous: false, hideFromNav: false, navGroup: nav('admin'), isDefaultLanding: false, isEnabled: true, order: 50, icon: 'LineChart', accessDeniedBehavior: 'render_access_denied', matchPrefixes: ['/admin/analytics'] }),
  route({ id: 'admin.support', path: '/admin/services/support-requests', moduleKey: 'support', routeType: 'admin', label: 'Support Requests', requiredPermissions: [{ resource: 'support_ticket', action: 'read' }], requiredFeatureFlags: [], requiredTenantCapabilities: [], requiredModules: ['support'], allowAnonymous: false, hideFromNav: false, navGroup: nav('admin'), isDefaultLanding: false, isEnabled: true, order: 60, icon: 'LifeBuoy', accessDeniedBehavior: 'render_access_denied', matchPrefixes: ['/admin/services/support-requests'] }),
  route({ id: 'admin.documents', path: '/admin/documents', moduleKey: 'documents', routeType: 'admin', label: 'Documents', requiredPermissions: [{ resource: 'document', action: 'read' }], requiredFeatureFlags: [], requiredTenantCapabilities: [], requiredModules: ['documents'], allowAnonymous: false, hideFromNav: false, navGroup: nav('admin'), isDefaultLanding: false, isEnabled: true, order: 70, icon: 'FileText', accessDeniedBehavior: 'render_access_denied', matchPrefixes: ['/admin/documents', '/admin/docushare'] }),
  route({ id: 'admin.system', path: '/admin/system', moduleKey: 'admin', routeType: 'admin', label: 'System', requiredPermissions: [{ resource: 'admin_user', action: 'read' }], requiredFeatureFlags: ['admin_console'], requiredTenantCapabilities: [], requiredModules: ['admin'], allowAnonymous: false, hideFromNav: false, navGroup: nav('admin'), isDefaultLanding: false, isEnabled: true, order: 80, icon: 'Settings', accessDeniedBehavior: 'render_access_denied', matchPrefixes: ['/admin/system', '/admin/users', '/admin/notifications', '/admin/audit-logs'] }),
];

export function getAllRouteDefinitions() {
  return [...PLATFORM_ROUTE_DEFINITIONS].sort((a, b) => a.order - b.order);
}

export function getRouteDefinition(pathname: string) {
  return getAllRouteDefinitions().find((definition) => {
    if (definition.path === pathname) return true;
    return (definition.matchPrefixes ?? []).some((prefix) => pathname.startsWith(prefix));
  });
}

export function listRoutesForModule(moduleKey: RouteDefinition['moduleKey']) {
  return getAllRouteDefinitions().filter((routeDefinition) => routeDefinition.moduleKey === moduleKey);
}
